"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronRight, Activity, BookOpen, Clock, Sparkles, FileText, ExternalLink } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import BackgroundCanvas from "@/components/BackgroundCanvas";

type Session = {
  id: string;
  query: string;
  status?: string;
  created_at: string;
  report?: string;
  source_urls?: string[];
  structured_refs?: { id: number; url: string; domain: string; title: string }[];
  citations?: { url: string; domain: string }[];
  metrics?: Record<string, unknown>;
};

export default function HistoryPage() {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const apiBase = process.env.NEXT_PUBLIC_API_URL || '';
        const res = await fetch(`${apiBase}/api/v1/sessions`);
        if (res.ok) {
          const data = await res.json();
          setSessions(data);
        }
      } catch (err) {
        console.error("Failed to fetch sessions", err);
      } finally {
        setIsLoading(false);
      }
    };
    fetchHistory();
  }, []);

  return (
    <main className="min-h-screen relative bg-black text-white p-4 sm:p-8 md:p-12 lg:p-16 pb-32 max-w-5xl mx-auto w-full pt-16">
      {/* Background Canvas */}
      <BackgroundCanvas />

      {/* HEADER SECTION */}
      <motion.div
        initial={{ opacity: 0, y: -16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="mb-10 space-y-3 relative z-10"
      >
        <div className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-4 py-1.5 text-xs font-mono font-semibold tracking-wider text-white shadow-[0_0_20px_rgba(255,255,255,0.15)]">
          <Sparkles className="h-3.5 w-3.5" />
          <span>REX Research Archive & Telemetry Logs</span>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl sm:text-4xl font-black font-display tracking-tight text-white flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-white text-black font-bold flex items-center justify-center shadow-md">
                <Clock className="w-5 h-5" strokeWidth={2.5} />
              </div>
              Research History
            </h1>
            <p className="text-zinc-300 mt-2 max-w-xl text-sm leading-relaxed">
              Complete historical record of research reports, scraped sources, and verified citations generated by REX.
            </p>
          </div>

          <div className="flex items-center gap-2 self-start sm:self-auto rounded-xl border border-white/25 bg-zinc-950 p-2.5 font-mono text-xs text-white shadow-md">
            <FileText className="h-4 w-4 text-white" />
            <span>Total Sessions: <strong className="text-white font-bold">{sessions.length}</strong></span>
          </div>
        </div>
      </motion.div>

      {/* CONTENT AREA */}
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-20 space-y-4">
          <span className="w-9 h-9 rounded-full border-2 border-white/30 border-t-white animate-spin" />
          <p className="text-xs text-zinc-400 font-mono uppercase tracking-widest">Retrieving Historical Sessions...</p>
        </div>
      ) : sessions.length === 0 ? (
        <motion.div
          initial={{ opacity: 0, scale: 0.96 }}
          animate={{ opacity: 1, scale: 1 }}
          className="rounded-2xl border border-white/25 bg-zinc-950 p-12 text-center space-y-4 shadow-[0_15px_45px_rgba(0,0,0,0.9)]"
        >
          <Activity className="w-12 h-12 text-zinc-600 mx-auto" strokeWidth={1.5} />
          <h3 className="text-base font-bold font-display text-white">No Research Runs Recorded Yet</h3>
          <p className="text-xs text-zinc-400 max-w-md mx-auto leading-relaxed">
            Execute your first research query in the workspace to automatically generate and persist report telemetry.
          </p>
        </motion.div>
      ) : (
        <div className="space-y-4 relative z-10">
          {sessions.map((session, i) => {
            const isExpanded = expandedId === session.id;
            const structuredRefs = session.structured_refs || [];
            const sourceUrls = session.source_urls || [];
            const citations = structuredRefs.length > 0
              ? structuredRefs
              : sourceUrls.map((url) => {
                  try { return { url, domain: new URL(url).hostname.replace(/^www\./, "") }; }
                  catch { return { url, domain: url }; }
                }).filter((c) => c.url);

            return (
              <motion.div
                key={session.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-30px" }}
                transition={{ duration: 0.4, delay: i * 0.04 }}
                className="rounded-2xl border border-white/25 bg-zinc-950 overflow-hidden shadow-[0_10px_35px_rgba(0,0,0,0.8)] hover:border-white hover:shadow-[0_15px_45px_rgba(255,255,255,0.2)] transition-all duration-300 card-hover-tilt"
              >
                <button
                  onClick={() => setExpandedId(isExpanded ? null : session.id)}
                  className="w-full p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-zinc-900 transition-colors text-left"
                >
                  <div className="flex-1 space-y-2 pr-4">
                    <h3 className="text-base sm:text-lg font-bold font-display text-white leading-snug">
                      {session.query}
                    </h3>

                    <div className="flex flex-wrap items-center gap-3">
                      <span className="flex items-center gap-1.5 text-xs text-zinc-400 font-mono">
                        <Clock className="w-3.5 h-3.5 text-white" />
                        {new Date(session.created_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                      </span>

                      {citations.length > 0 && (
                        <span className="flex items-center gap-1.5 text-xs font-mono font-semibold text-white bg-white/15 px-2.5 py-0.5 rounded-md border border-white/30">
                          <BookOpen className="w-3.5 h-3.5" />
                          {citations.length} Verified Sources
                        </span>
                      )}

                      <span className="text-[10px] uppercase font-bold font-mono tracking-wider px-2.5 py-0.5 rounded-md bg-white/15 text-white border border-white/30">
                        {session.status || "completed"}
                      </span>
                    </div>
                  </div>

                  <div className={`flex-shrink-0 w-9 h-9 rounded-xl border border-white/30 flex items-center justify-center transition-transform duration-300 ${isExpanded ? 'rotate-90 bg-white text-black font-bold' : 'bg-black text-white'}`}>
                    <ChevronRight className="w-4 h-4" />
                  </div>
                </button>

                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
                      className="border-t border-white/15 bg-black p-6 sm:p-8 space-y-6"
                    >
                      {session.report ? (
                        <article className="prose prose-invert max-w-none prose-sm text-left">
                          <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
                            {session.report}
                          </ReactMarkdown>
                        </article>
                      ) : (
                        <p className="text-xs text-zinc-500 italic">Report details were not saved or session was interrupted.</p>
                      )}
                      
                      {citations.length > 0 && (
                        <div className="pt-6 border-t border-white/15 space-y-3">
                          <h4 className="text-xs font-bold uppercase tracking-wider font-mono text-white flex items-center gap-2">
                            <BookOpen className="w-4 h-4 text-white" />
                            Analyzed & Cited Primary Sources ({citations.length})
                          </h4>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                            {citations.map((cite, idx) => (
                              <a
                                key={idx}
                                href={cite.url}
                                target="_blank"
                                rel="noreferrer"
                                className="flex items-center gap-3 p-3 rounded-xl border border-white/20 bg-zinc-950 hover:border-white hover:bg-zinc-900 transition-colors group"
                              >
                                <div className="w-6 h-6 shrink-0 rounded-lg bg-white/15 text-white font-mono font-bold text-[10px] flex items-center justify-center border border-white/30">
                                  {idx + 1}
                                </div>
                                <div className="min-w-0 flex-1">
                                  <p className="text-xs font-bold text-white truncate group-hover:underline transition-colors">
                                    {cite.domain}
                                  </p>
                                  <p className="text-[10px] text-zinc-400 font-mono truncate mt-0.5">{cite.url}</p>
                                </div>
                                <ExternalLink className="h-3.5 w-3.5 text-zinc-400 group-hover:text-white shrink-0" />
                              </a>
                            ))}
                          </div>
                        </div>
                      )}
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      )}
    </main>
  );
}
